export const data: {
    teeDate: string
    distance: number
    address: string
    cover: string
    holeNum: number
    minPrice: number
    name: string
    originalPrice: number
    bookingPolicy: string
    region: number
    partnerType: string
    star: number
    aboutUsUrl: string
    id: number
    giaOriginalNgayCuoiTuan?: number
    giaNgayCuoiTuan?: number
    giaOriginalNgayLe?: number
    giaNgayLe?: number
    giaOriginalNgayThuong: number
    giaNgayThuong: number
    describe: string
    city: string
    nameKana: string
}[] = [
        {
            "teeDate": "2023-07-20",
            "distance": 640,
            "address": "Duy Xuyen District, \nQuang Nam Province, Vietnam",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2020/03/Unknown.jpg",
            "holeNum": 18,
            "minPrice": 2100000,
            "name": "Hoiana Shores Golf Club",
            "originalPrice": 2600000,
            "bookingPolicy": "Policy",
            "region": 2,
            "partnerType": "1",
            "star": 4,
            "aboutUsUrl": "https://www.hoiana.com/vn/golf/",
            "id": 154,
            "giaOriginalNgayCuoiTuan": 3500000,
            "giaNgayCuoiTuan": 2350000,
            "giaOriginalNgayLe": 2600000,
            "giaNgayLe": 2000000,
            "giaOriginalNgayThuong": 2600000,
            "giaNgayThuong": 2000000,
            "describe": "ホイアナショアーズゴルフクラブは、ベトナムのダナン市に位置し、美しい海岸線に隣接しています。このゴルフコースは、自然の景観と巧妙なデザインが組み合わさり、ゴルファーにとって楽しいプレイを提供します。フェアウェイとグリーンは非常によくメンテナンスされており、ゴルフのスキルに挑戦できる素晴らしい場所です。また、クラブハウスには高級な設備が充実しており、リラックスした雰囲気でゴルフを楽しむことができます。ホイアナショアーズは、ベトナムのゴルフ体験を求めるゴルファーにとって魅力的な場所の1つです。",
            "city": "クアンナム",
            "nameKana": "ホアナ ショアーズ ゴルフ クラブ"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 34,
            "address": "Ngọc Thanh commune, Phuc Yên district, Vinh Phuc province",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1554706675.jpg",
            "holeNum": 18,
            "minPrice": 1650000,
            "name": "Dai Lai Golf Club",
            "originalPrice": 1750000,
            "bookingPolicy": "Fastee's Policy",
            "region": 1,
            "partnerType": "1",
            "star": 3,
            "aboutUsUrl": "http://dailaigolf.com.vn/",
            "id": 51,
            "giaOriginalNgayCuoiTuan": 3050000,
            "giaNgayCuoiTuan": 2950000,
            "giaOriginalNgayLe": 2650000,
            "giaNgayLe": 2950000,
            "giaOriginalNgayThuong": 1850000,
            "giaNgayThuong": 1850000,
            "describe": "ダイライゴルフクラブは、ベトナムのハノイからわずか数キロの距離に位置し、静かなダイライ湖の景観に囲まれています。このコースは、美しい自然環境の中でゴルフを楽しむための絶好の場所です。フェアウェイは広々としており、初心者から上級者まで、さまざまなレベルのゴルファーに対応しています。クラブハウスには設備が整っており、ゴルフ後のリラックスに最適です。ダイライゴルフクラブは、都市の喧騒から離れ、自然の美しさを堪能しながらゴルフを楽しむ場所としておすすめです。",
            "city": "ビンフック",
            "nameKana": "ダイ ライ ゴルフ クラブ"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 1047,
            "address": "Hon Tre island, Nha Trang, Khanh Hoa provice",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1531822397.jpg",
            "holeNum": 18,
            "minPrice": 2200000,
            "name": "Vinpearl Golf Club Nha Trang",
            "originalPrice": 2970000,
            "bookingPolicy": "Fastee's Policy",
            "region": 2,
            "partnerType": "1",
            "star": 5,
            "aboutUsUrl": "https://vinpearl.com/vi/vingolf",
            "id": 139,
            "giaOriginalNgayCuoiTuan": 4050000,
            "giaNgayCuoiTuan": 2650000,
            "giaOriginalNgayLe": 2375000,
            "giaNgayLe": 2200000,
            "giaOriginalNgayThuong": 2375000,
            "giaNgayThuong": 2200000,
            "describe": "ヴィンパールゴルフクラブは、ベトナムのニャチャンに位置し、美しいビーチフロントの景色と組み合わさった高品質なゴルフ体験を提供します。このコースは、トロピカルな気候と息をのむような海岸線の風景を楽しむ絶好の場所です。フェアウェイとグリーンは非常にメンテナンスが行き届いており、ゴルフラウンドを満喫することができます。ヴィンパールゴルフクラブは、リゾート地にあるため、プレイヤーには充実した施設が提供されます。ゴルフ愛好家にとって、ニャチャンでの滞在中に訪れる価値がある場所です。",
            "city": "カインホア",
            "nameKana": "ヴィンパール ゴルフ クラブ ニャチャン"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 35,
            "address": "Dinh Am, Khai Quang, Vinh Yen town, Vinh Phuc province.",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1554708240.jpg",
            "holeNum": 18,
            "minPrice": 2100000,
            "name": "Heron Lake Golf Course & Resort (Dam Vac)",
            "originalPrice": 2000000,
            "bookingPolicy": "Fastee's Policy",
            "region": 1,
            "partnerType": "1",
            "star": 2,
            "aboutUsUrl": "http://cengolf.vn/",
            "id": 18,
            "giaOriginalNgayCuoiTuan": 3100000,
            "giaNgayCuoiTuan": 3050000,
            "giaOriginalNgayLe": 3100000,
            "giaNgayLe": 3000000,
            "giaOriginalNgayThuong": 2000000,
            "giaNgayThuong": 2150000,
            "describe": "ヘロンレイクゴルフコース＆リゾート（ダムヴァク）は、ハノイから車で簡単にアクセスできる場所に位置し、美しい湖畔の景色を楽しむことができるゴルフコースです。このコースは、青々としたフェアウェイと巧妙なデザインが特徴で、ゴルフプレイヤーにとって理想的な環境を提供します。クラブハウスは快適なリラックススペースを提供し、プレイヤーたちに素晴らしい体験を提供します。ヘロンレイクゴルフコースは、自然の美しさと高品質なゴルフ体験を求めるゴルファーにとって魅力的な選択肢です。",
            "city": "ヴィンフック",
            "nameKana": "ヘロン レイク ゴルフ コース & リゾート (ダム ヴァク)"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 620,
            "address": "Hoà Hải, Ngũ Hành Sơn, Đà Nẵng",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1559812650.jpg",
            "holeNum": 18,
            "minPrice": 2450000,
            "name": "BRG Da Nang Golf Resort",
            "originalPrice": 3300000,
            "bookingPolicy": "Fastee's Policy",
            "region": 2,
            "partnerType": "1",
            "star": 4,
            "aboutUsUrl": "http://dananggolf.com.vn/",
            "id": 122,
            "giaOriginalNgayCuoiTuan": 4500000,
            "giaNgayCuoiTuan": 3600000,
            "giaOriginalNgayLe": 4500000,
            "giaNgayLe": 3600000,
            "giaOriginalNgayThuong": 3300000,
            "giaNgayThuong": 2400000,
            "describe": "BRGダナンゴルフリゾートは、ベトナムのダナン市に位置し、ゴルフラウンドとリゾートの魅力を組み合わせた素晴らしい場所です。このゴルフコースは、美しい海岸線に隣接し、景色が壮観です。フェアウェイとグリーンは高品質でメンテナンスが行き届いており、プレイヤーに素晴らしいゴルフ体験を提供します。クラブハウスには充実した設備があり、ゴルフ後のリラックスや食事に最適です。BRGダナンゴルフリゾートは、ベトナムのゴルフ愛好家にとって訪れる価値がある場所の1つです。",
            "city": "ダナン",
            "nameKana": "BRG ダ ナン ゴルフ リゾート"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 1048,
            "address": "Phuoc Ha Hamlet, Phuoc Dong Commune, Phước Đồng, Thành phố Nha Trang, Khánh Hòa",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1559286379.jpg",
            "holeNum": 18,
            "minPrice": 2100000,
            "name": "Diamond Bay Golf & Villas",
            "originalPrice": 3100000,
            "bookingPolicy": "Fastee's Policy",
            "region": 2,
            "partnerType": "1",
            "star": 3,
            "aboutUsUrl": "http://www.diamondbaygolfvillas.com/vi",
            "id": 119,
            "giaOriginalNgayCuoiTuan": 4340000,
            "giaNgayCuoiTuan": 2400000,
            "giaOriginalNgayLe": 3100000,
            "giaNgayLe": 2100000,
            "giaOriginalNgayThuong": 3100000,
            "giaNgayThuong": 2100000,
            "describe": "ダイヤモンドベイゴルフ＆ヴィラは、ベトナムのニャチャンに位置し、トロピカルなリゾート体験と高品質なゴルフを提供します。このゴルフコースは、海岸線に沿って広がり、ゴルフプレイヤーに美しい景色を楽しむ機会を提供します。フェアウェイとグリーンは非常によくメンテナンスされており、ゴルフ愛好家にとって理想的な場所です。クラブハウスはリラックスできる場所であり、レストランやバーも充実しています。ダイヤモンドベイゴルフ＆ヴィラは、ベトナムでのリゾートゴルフを楽しみたい人々にとって素晴らしい選択肢です。",
            "city": "ナトラン",
            "nameKana": "ダイヤモンド ベイ ゴルフ & ヴィラス"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 1048,
            "address": "2 Đường Trần Nhân Tông, Phường 8, Thành phố Đà Lạt, Lâm Đồng, Vietnam",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1559287552.jpg",
            "holeNum": 18,
            "minPrice": 1750000,
            "name": "Dalat Palace Golf Club",
            "originalPrice": 1900000,
            "bookingPolicy": "Fastee's Policy",
            "region": 2,
            "partnerType": "1",
            "star": 2,
            "aboutUsUrl": "https://www.dalatpalacegolf.com/index.php/vi/",
            "id": 118,
            "giaOriginalNgayCuoiTuan": 3000000,
            "giaNgayCuoiTuan": 2500000,
            "giaOriginalNgayThuong": 2800000,
            "giaNgayThuong": 2200000,
            "describe": "ダラットパレスゴルフクラブは、ベトナムのダラットに位置し、美しい山岳地帯の中にあるゴルフコースです。このコースは、自然の景観と共に、ゴルフプレイヤーに挑戦的なプレイを提供します。フェアウェイとグリーンは高品質で、設備も整っており、プレイヤーたちに快適な滞在を提供します。クラブハウスからはダラットの美しい景色を一望できます。ダラットパレスゴルフクラブは、ベトナムのゴルフ愛好家や観光客にとって、山岳地帯での贅沢なゴルフ体験を楽しむ場所として知られています。",
            "city": "ダラット",
            "nameKana": "ダラット パレス ゴルフ クラブ"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 33,
            "address": "Hanoi",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1554706801.jpg",
            "holeNum": 18,
            "minPrice": 2700000,
            "name": "BRG Kings Island Golf Resort - King Course",
            "originalPrice": 3500000,
            "bookingPolicy": "Fastee's Policy",
            "region": 1,
            "partnerType": "1",
            "star": 4,
            "aboutUsUrl": "http://brgkingsislandgolf.vn/1/15/Trang-chu.aspx",
            "id": 115,
            "giaOriginalNgayCuoiTuan": 4200000,
            "giaNgayCuoiTuan": 3550000,
            "giaOriginalNgayLe": 3950000,
            "giaNgayLe": 3550000,
            "giaOriginalNgayThuong": 3800000,
            "giaNgayThuong": 2800000,
            "describe": "BRGキングスアイランドゴルフリゾートのキングコースは、ハノイ近郊に位置し、湖と自然の美しさに囲まれたゴルフコースです。このコースは、チャレンジングなデザインと美しい景色を組み合わせ、ゴルフプレイヤーに楽しさと挑戦を提供します。フェアウェイとグリーンは高品質でメンテナンスが行き届いており、プレイヤーたちはゴルフを楽しむことができます。クラブハウスには充実の施設があり、ゴルフ後のリラックスに最適です。BRGキングスアイランドのキングコースは、ベトナムのゴルフラバーにとって魅力的な場所の1つです。",
            "city": "ハノイ",
            "nameKana": "BRG キングス アイランド ゴルフ リゾート - キング コース"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 250,
            "address": "Nghi Hương, Cửa Lò, Nghệ An",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1558055775.jpg",
            "holeNum": 18,
            "minPrice": 1550000,
            "name": "Cua Lo Golf Resort",
            "originalPrice": 1635000,
            "bookingPolicy": "Fastee's Policy",
            "region": 2,
            "partnerType": "1",
            "star": 2,
            "aboutUsUrl": "http://cualogolfresort.com.vn/",
            "id": 113,
            "giaOriginalNgayCuoiTuan": 2605000,
            "giaNgayCuoiTuan": 2300000,
            "giaOriginalNgayLe": 2605000,
            "giaNgayLe": 2300000,
            "giaOriginalNgayThuong": 2605000,
            "giaNgayThuong": 1700000,
            "describe": "クアロゴルフリゾートは、ベトナムのクアロに位置し、美しい海岸線と自然の景観に囲まれたゴルフコースです。このコースは、リラックスした雰囲気と高品質なゴルフプレイを提供します。フェアウェイとグリーンは非常にメンテナンスが行き届いており、ゴルフ愛好家にとって魅力的な場所です。クラブハウスは快適な施設で充実しており、プレイヤーたちはゴルフの後にくつろぐことができます。クアロゴルフリゾートは、海岸線での素晴らしいゴルフ体験を求める人々にとって魅力的な選択肢です。",
            "city": "クアロ",
            "nameKana": "クア ロ ゴルフ リゾート"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 1194,
            "address": "Số 01 Thùy Vân, Thành phố Vũng Tầu, Bà Rịa - Vũng Tàu, Vietnam",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1559289488.jpg",
            "holeNum": 18,
            "minPrice": 2200000,
            "name": "Vung Tau Paradise Resort Golf Club",
            "originalPrice": 2300000,
            "bookingPolicy": "Fastee's Policy",
            "region": 3,
            "partnerType": "1",
            "star": 3,
            "aboutUsUrl": "http://www.golfparadise.com.vn/",
            "id": 135,
            "giaOriginalNgayCuoiTuan": 2725000,
            "giaNgayCuoiTuan": 2900000,
            "giaOriginalNgayLe": 2300000,
            "giaNgayLe": 2900000,
            "giaOriginalNgayThuong": 2300000,
            "giaNgayThuong": 2200000,
            "describe": "ブンタウパラダイスリゾートゴルフクラブは、ベトナムのブンタウに位置し、美しい海岸線と緑豊かな景観が魅力のゴルフコースです。このコースは、ゴルフプレイヤーにリゾート体験とゴルフの両方を提供します。フェアウェイとグリーンは高品質で、ゴルフを楽しむための理想的な条件を提供します。クラブハウスには充実の施設があり、プレイヤーたちはリラックスした雰囲気で滞在できます。ブンタウパラダイスリゾートゴルフクラブは、ベトナムのゴルフ愛好家にとって訪れる価値がある場所です。",
            "city": "ヴンタウ",
            "nameKana": "ヴォン タウ パラダイス リゾート ゴルフ クラブ"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 644,
            "address": "Đường Thanh Niên, Xã Bình Dương, Huyện Thăng Bình, Tỉnh Quảng Nam, Việt Nam\n15.798258, 108.420530",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/09/download_1.jpeg",
            "holeNum": 18,
            "minPrice": 2200000,
            "name": "Vinpearl Golf Nam Hội An",
            "originalPrice": 3025000,
            "bookingPolicy": "Fastee's Policy",
            "region": 2,
            "partnerType": "1",
            "star": 4,
            "aboutUsUrl": "https://vinpearl.com/vi/vingolf",
            "id": 136,
            "giaOriginalNgayCuoiTuan": 3075000,
            "giaNgayCuoiTuan": 2650000,
            "giaOriginalNgayLe": 3025000,
            "giaNgayLe": 2250000,
            "giaOriginalNgayThuong": 3025000,
            "giaNgayThuong": 2200000,
            "describe": "ヴィンパールゴルフナムホイアンは、ベトナムのホイアンに位置し、美しいビーチフロントとゴルフの組み合わせでゴルファーに魅力的な場所です。このコースは、トロピカルな気候と素晴らしい景色を提供し、ゴルフを楽しむプレイヤーに楽しさを提供します。フェアウェイとグリーンは高品質でメンテナンスが行き届いており、プレイヤーたちは快適にプレイできます。ヴィンパールゴルフナムホイアンは、リゾート施設も充実しており、ゴルフ以外のアクティビティも楽しめます。ホイアンでの滞在中に、ヴィンパールゴルフを楽しんでください。",
            "city": "ホイアン",
            "nameKana": "ヴィンパール ゴルフ ナム ホイアン"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 1072,
            "address": "KN Paradise / KN Golf Links Road, Cam Hải Đông, Tp. Cam Ranh, Khánh Hòa",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/09/KN_Golf_Links.jpg",
            "holeNum": 18,
            "minPrice": 2100000,
            "name": "KN Golf Links Cam Ranh",
            "originalPrice": 3375000,
            "bookingPolicy": "Fastee's Policy",
            "region": 2,
            "partnerType": "1",
            "star": 4,
            "aboutUsUrl": "https://www.kngolflinks.com/vi-VN/san-golf",
            "id": 138,
            "giaOriginalNgayCuoiTuan": 4500000,
            "giaNgayCuoiTuan": 2550000,
            "giaOriginalNgayLe": 2350000,
            "giaNgayLe": 2150000,
            "giaOriginalNgayThuong": 2350000,
            "giaNgayThuong": 2150000,
            "describe": "KNゴルフリンクスカムランは、ベトナムのカムランに位置し、美しい海岸線の景色と高品質なゴルフプレイを提供します。このコースは、トロピカルなリゾート体験とゴルフを組み合わせており、訪れる価値があります。フェアウェイとグリーンは非常にメンテナンスが行き届いており、プレイヤーたちはゴルフを楽しむことができます。クラブハウスは快適な雰囲気で、プレイヤーたちはリラックスできます。KNゴルフリンクスカムランは、ベトナムのゴルフ愛好家にとって魅力的な場所です。",
            "city": "カムラン",
            "nameKana": "KN ゴルフ リンクス カム ラン"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 1186,
            "address": "Phuoc Thuan, Xuyen Moc, Ba Ria - Vung Tau, Vietnam",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1531821869.jpg",
            "holeNum": 18,
            "minPrice": 3200000,
            "name": "The Bluffs Ho Tram Strip",
            "originalPrice": 5124000,
            "bookingPolicy": "Fastee's Policy",
            "region": 3,
            "partnerType": "1",
            "star": 5,
            "aboutUsUrl": "https://thebluffshotram.com/",
            "id": 142,
            "giaOriginalNgayThuong": 4422000,
            "giaNgayThuong": 3200000,
            "describe": "ザブラフスホーチャムストリップは、ベトナムのホーチャムに位置し、美しい海岸線の景色と難しいゴルフプレイを提供します。このコースは、ゴルフプレイヤーに挑戦的なプレイを楽しむ機会を提供し、美しい自然環境を満喫できます。フェアウェイとグリーンは高品質でメンテナンスが行き届いており、プレイヤーたちはゴルフの腕前を試すことができます。クラブハウスは快適で設備が充実しており、ゴルフ後のリラックスに最適です。ザブラフスホーチャムストリップは、ベトナムのゴルフ愛好家にとって特に要注目のコースの1つです。",
            "city": "ヴンタウ",
            "nameKana": "ザ ブラフス ホー トラム ストリップ"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 211,
            "address": "xóm Đồng Nông, Diễn Lâm, Diễn Châu, Nghệ An",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2020/03/62208987_2440997772843905_8577376824886034432_n.jpg",
            "holeNum": 18,
            "minPrice": 1450000,
            "name": "Muong Thanh Golf Club Diễn Lâm",
            "originalPrice": 1550000,
            "bookingPolicy": "Update",
            "region": 2,
            "partnerType": "1",
            "star": 2,
            "aboutUsUrl": "http://muongthanh.com/",
            "id": 155,
            "giaOriginalNgayCuoiTuan": 2500000,
            "giaNgayCuoiTuan": 2200000,
            "giaOriginalNgayLe": 2500000,
            "giaNgayLe": 2200000,
            "giaOriginalNgayThuong": 1550000,
            "giaNgayThuong": 1450000,
            "describe": "ムオンタンゴルフクラブディエンラムは、ベトナムのディエンラムに位置し、美しい山岳地帯に囲まれたゴルフコースです。このコースは、ゴルフプレイヤーに自然の美しさと挑戦的なプレイを提供します。フェアウェイとグリーンは高品質でメンテナンスが行き届いており、ゴルフを楽しむための理想的な条件を提供します。クラブハウスは快適で、ゴルフ後のリラックスに最適です。ディエンラムでゴルフを楽しむ際に、ムオンタンゴルフクラブを訪れてみてください。",
            "city": "ディエンラム",
            "nameKana": "ムオン タン ゴルフ クラブ ディエン ラム"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 89,
            "address": "Ky Phu Ward, Nho Quan District, Ninh Binh",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1554706816.jpg",
            "holeNum": 18,
            "minPrice": 1500000,
            "name": "Trang An Golf & Country Club",
            "originalPrice": 1750000,
            "bookingPolicy": "Fastee's Policy",
            "region": 1,
            "partnerType": "1",
            "star": 3,
            "aboutUsUrl": "http://trangangolf.com/2/Gi%E1%BB%9Bi-thi%E1%BB%87u",
            "id": 93,
            "giaOriginalNgayCuoiTuan": 2600000,
            "giaNgayCuoiTuan": 2250000,
            "giaOriginalNgayLe": 1750000,
            "giaNgayLe": 2250000,
            "giaOriginalNgayThuong": 1750000,
            "giaNgayThuong": 1550000,
            "describe": "トランアンゴルフ＆カントリークラブは、ベトナムのホアビンに位置し、美しい山岳地帯と湖畔の景色に囲まれたゴルフコースです。このコースは、ゴルフプレイヤーに自然の美しさと楽しさを提供します。フェアウェイとグリーンは高品質でメンテナンスが行き届いており、ゴルフを楽しむための素晴らしい環境を提供します。クラブハウスは快適で、リラックスできる場所です。トランアンゴルフ＆カントリークラブは、ホアビンでゴルフを楽しむ際に訪れる価値がある場所です。",
            "city": "ニンビン",
            "nameKana": "トラン アン ゴルフ & カントリー クラブ"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 35,
            "address": "Lâm Sơn, Lương Sơn, Hòa Bình, Việt Nam",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1557734270.jpg",
            "holeNum": 18,
            "minPrice": 1700000,
            "name": "Phoenix Golf & Resort (Vietnamese golfers only)",
            "originalPrice": 1800000,
            "bookingPolicy": "Fastee's Policy",
            "region": 1,
            "partnerType": "1",
            "star": 1,
            "aboutUsUrl": "http://phoenixgolf.kr/index_en.html",
            "id": 158,
            "giaOriginalNgayCuoiTuan": 2705000,
            "giaNgayCuoiTuan": 2600000,
            "giaOriginalNgayLe": 1800000,
            "giaNgayLe": 2600000,
            "giaOriginalNgayThuong": 1800000,
            "giaNgayThuong": 1700000,
            "describe": "フェニックスゴルフ＆リゾートは、ベトナムのホーチャムに位置し、ベトナムのゴルフ愛好家向けに提供されているゴルフコースです。このコースは、美しい自然環境と高品質なゴルフプレイを組み合わせ、プレイヤーに楽しさを提供します。フェアウェイとグリーンは非常によくメンテナンスされており、ゴルフ体験を楽しむことができます。クラブハウスはリラックスできる場所であり、ゴルフ後のくつろぎに最適です。フェニックスゴルフ＆リゾートは、ベトナムのゴルファーにとって特別な場所で、リゾートゴルフを楽しむ絶好の機会を提供します。",
            "city": "ホアビン",
            "nameKana": "フェニックス ゴルフ & リゾート (ベトナムゴルファー専用)"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 46,
            "address": "Thôn Bình An, Xã, Tiền Phong, Yên Dũng, Bắc Giang",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1554706756.jpg",
            "holeNum": 18,
            "minPrice": 1650000,
            "name": "AMBER HILLS GOLF & RESORT (Yen Dung Golf)",
            "originalPrice": 2650000,
            "bookingPolicy": "Fastee's Policy",
            "region": 1,
            "partnerType": "1",
            "star": 3,
            "aboutUsUrl": "https://yendunggolf.vn/",
            "id": 89,
            "giaOriginalNgayCuoiTuan": 3450000,
            "giaNgayCuoiTuan": 2700000,
            "giaOriginalNgayLe": 2650000,
            "giaNgayLe": 2700000,
            "giaOriginalNgayThuong": 1700000,
            "giaNgayThuong": 1650000,
            "describe": "AMBER HILLSゴルフ＆リゾート（イェンダンゴルフ）は、ベトナムのイェンダンに位置し、美しい自然景観と高品質なゴルフプレイを提供します。このゴルフコースは、フェアウェイとグリーンが非常によくメンテナンスされており、ゴルファーに理想的なプレイ環境を提供します。クラブハウスはリラックスできる場所であり、プレイヤーたちはゴルフ後にくつろぐことができます。AMBER HILLSゴルフ＆リゾートは、ベトナムのゴルフ愛好家にとって魅力的な選択肢の1つです。",
            "city": "バックザン",
            "nameKana": "アンバーヒルズ ゴルフ & リゾート (イエン ダン ゴルフ)"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 267,
            "address": "Thôn Thành Vân, Nghi Xuân, Hà Tĩnh",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2021/03/62459652_286357395463209_1331742094313652224_o.png",
            "holeNum": 18,
            "minPrice": 1500000,
            "name": "Mường Thanh Xuân Thành",
            "originalPrice": 1600000,
            "bookingPolicy": "Update.",
            "region": 2,
            "partnerType": "1",
            "star": 2,
            "aboutUsUrl": "http://xuanthanhgolfclub.muongthanh.com/",
            "id": 162,
            "giaOriginalNgayCuoiTuan": 2500000,
            "giaNgayCuoiTuan": 2300000,
            "giaOriginalNgayLe": 2500000,
            "giaNgayLe": 2300000,
            "giaOriginalNgayThuong": 1600000,
            "giaNgayThuong": 1500000,
            "describe": "ムオンタンシュアンタンは、ベトナムのシュアンタンに位置し、美しい山岳地帯の中にあるゴルフコースです。このコースは、自然の美しさと挑戦的なプレイを楽しむための理想的な場所です。フェアウェイとグリーンは高品質でメンテナンスが行き届いており、ゴルフプレイヤーに素晴らしい環境を提供します。クラブハウスは快適な場所で、プレイヤーたちはゴルフ後にくつろぐことができます。シュアンタンでゴルフを楽しむ際に、ムオンタンシュアンタンを訪れてみてください。",
            "city": "ハティン",
            "nameKana": "ムオン タン シュアン タン"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 29,
            "address": "Van Son Commune, Chuong My Dist, Ha Noi city",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1554706734.jpg",
            "holeNum": 18,
            "minPrice": 2250000,
            "name": "Sky Lake Resort & Golf Club - Sky Course",
            "originalPrice": 3600000,
            "bookingPolicy": "Fastee's Policy",
            "region": 1,
            "partnerType": "1",
            "star": 3,
            "aboutUsUrl": "http://www.skylakegolfclub.vn/Vietnam/",
            "id": 116,
            "giaOriginalNgayCuoiTuan": 3600000,
            "giaNgayCuoiTuan": 3500000,
            "giaOriginalNgayLe": 3600000,
            "giaNgayLe": 3500000,
            "giaOriginalNgayThuong": 2300000,
            "giaNgayThuong": 2250000,
            "describe": "スカイレイクリゾート＆ゴルフクラブのスカイコースは、ベトナムのハノイに位置し、美しい山岳地帯と湖畔の景色に囲まれたゴルフコースです。このコースは、ゴルフプレイヤーに挑戦的なプレイと自然の美しさを提供します。フェアウェイとグリーンは高品質で、プレイヤーたちはゴルフを楽しむことができます。クラブハウスには充実の施設があり、リラックスできる場所です。スカイレイクリゾート＆ゴルフクラブのスカイコースは、ハノイの近くでゴルフを楽しむための絶好の場所です。",
            "city": "ハノイ",
            "nameKana": "スカイ レイク リゾート & ゴルフ クラブ - スカイ コース"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 1135,
            "address": "1 Hoàng Hữu Nam, Long Thạnh Mỹ, Quận 9, Hồ Chí Minh",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1561017124.jpg",
            "holeNum": 18,
            "minPrice": 2350000,
            "name": "Viet Nam Golf & Country Club",
            "originalPrice": 2500000,
            "bookingPolicy": "Fastee's Policy",
            "region": 3,
            "partnerType": "1",
            "star": 2,
            "aboutUsUrl": "",
            "id": 134,
            "giaOriginalNgayCuoiTuan": 3600000,
            "giaNgayCuoiTuan": 3500000,
            "giaOriginalNgayLe": 2000000,
            "giaNgayLe": 2300000,
            "giaOriginalNgayThuong": 2500000,
            "giaNgayThuong": 2390000,
            "describe": "ベトナムゴルフ＆カントリークラブは、ベトナムのホーチミン市に位置し、ゴルフプレイヤーに高品質なゴルフ体験を提供します。このコースは、フェアウェイとグリーンが非常によくメンテナンスされており、ゴルフを楽しむための理想的な条件を提供します。クラブハウスには充実の施設があり、リラックスできる場所です。ベトナムゴルフ＆カントリークラブは、ホーチミン市でのゴルフ体験を求めるゴルファーにとって魅力的な選択肢の1つです。",
            "city": "ホーチミン",
            "nameKana": "ベトナム ゴルフ & カントリー クラブ"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 1136,
            "address": "Bien Hoa",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1560754196.jpg",
            "holeNum": 18,
            "minPrice": 1900000,
            "name": "Long Thanh Golf Club",
            "originalPrice": 2000000,
            "bookingPolicy": "Fastee's Policy",
            "region": 3,
            "partnerType": "1",
            "star": 3,
            "aboutUsUrl": "https://longthanhgolfresort.com/",
            "id": 126,
            "giaOriginalNgayCuoiTuan": 2600000,
            "giaNgayCuoiTuan": 2950000,
            "giaOriginalNgayLe": 2000000,
            "giaNgayLe": 1950000,
            "giaOriginalNgayThuong": 2000000,
            "giaNgayThuong": 1900000,
            "describe": "ロンタンゴルフクラブは、ベトナムのホーチミン市に位置し、美しいゴルフコースと高品質なプレイを提供します。このコースは、フェアウェイとグリーンが非常にメンテナンスが行き届いており、ゴルフを楽しむための素晴らしい場所です。クラブハウスはリラックスできる場所であり、プレイヤーたちはゴルフ後にくつろぐことができます。ロンタンゴルフクラブは、ホーチミン市でゴルフを楽しむための魅力的な選択肢です。",
            "city": "ビエンホア",
            "nameKana": "ロング タン ゴルフ クラブ"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 33,
            "address": "Hanoi",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1554706801.jpg",
            "holeNum": 18,
            "minPrice": 2600000,
            "name": "BRG Kings Island Golf Resort - Lakeside",
            "originalPrice": 3050000,
            "bookingPolicy": "Fastee's Policy",
            "region": 1,
            "partnerType": "1",
            "star": 4,
            "aboutUsUrl": "http://brgkingsislandgolf.vn/1/15/Trang-chu.aspx",
            "id": 149,
            "giaOriginalNgayCuoiTuan": 3950000,
            "giaNgayCuoiTuan": 3350000,
            "giaOriginalNgayLe": 3950000,
            "giaNgayLe": 3350000,
            "giaOriginalNgayThuong": 3050000,
            "giaNgayThuong": 2600000,
            "describe": "BRGキングスアイランドゴルフリゾートのレイクサイドコースは、ハノイ近郊に位置し、美しい湖畔の景色と高品質なゴルフプレイを提供します。このコースは、ゴルフプレイヤーに美しい自然環境と楽しさを提供します。フェアウェイとグリーンは非常にメンテナンスが行き届いており、ゴルフを楽しむための理想的な条件を提供します。クラブハウスには充実の施設があり、ゴルフ後のリラックスに最適です。BRGキングスアイランドのレイクサイドコースは、ベトナムのゴルフ愛好家にとって魅力的な場所です。",
            "city": "ハノイ",
            "nameKana": "BRG キングス アイランド ゴルフ リゾート - レイクサイド"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 1150,
            "address": "Km9, Nguyễn Thông, Phú Hài, Phan Thiết, Bình Thuận, Việt Nam",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1559901382.jpg",
            "holeNum": 18,
            "minPrice": 1900000,
            "name": "Sea Links Golf & Country Club",
            "originalPrice": 1950000,
            "bookingPolicy": "Fastee's Policy",
            "region": 3,
            "partnerType": "1",
            "star": 4,
            "aboutUsUrl": "https://www.sealinkscity.com/golf/",
            "id": 125,
            "giaOriginalNgayCuoiTuan": 2650000,
            "giaNgayCuoiTuan": 2750000,
            "giaOriginalNgayLe": 1950000,
            "giaNgayLe": 2750000,
            "giaOriginalNgayThuong": 1950000,
            "giaNgayThuong": 1850000,
            "describe": "シーリンクスゴルフ＆カントリークラブは、ベトナムのファンティエットに位置し、美しい海岸線の景色と高品質なゴルフプレイを提供します。このコースは、トロピカルなリゾート体験とゴルフを楽しむための素晴らしい場所です。フェアウェイとグリーンは非常にメンテナンスが行き届いており、ゴルフを楽しむための理想的な条件を提供します。クラブハウスはリラックスできる場所であり、ゴルフ後のくつろぎに最適です。シーリンクスゴルフ＆カントリークラブは、ファンティエットでのゴルフ体験を求めるゴルファーにとって魅力的な選択肢です。",
            "city": "ファンティエット",
            "nameKana": "シーリンクス ゴルフ & カントリー クラブ"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 33,
            "address": "Hanoi",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1554706801.jpg",
            "holeNum": 18,
            "minPrice": 2700000,
            "name": "BRG Kings Island Golf Resort - Moutain View",
            "originalPrice": 3150000,
            "bookingPolicy": "Fastee's Policy",
            "region": 1,
            "partnerType": "1",
            "star": 4,
            "aboutUsUrl": "http://brgkingsislandgolf.vn/1/15/Trang-chu.aspx",
            "id": 150,
            "giaOriginalNgayCuoiTuan": 4050000,
            "giaNgayCuoiTuan": 3450000,
            "giaOriginalNgayLe": 4050000,
            "giaNgayLe": 3450000,
            "giaOriginalNgayThuong": 3300000,
            "giaNgayThuong": 2700000,
            "describe": "BRGキングスアイランドゴルフリゾートのマウンテンビューコースは、ハノイ近郊に位置し、美しい山岳地帯の景色と高品質なゴルフプレイを提供します。このコースは、ゴルフプレイヤーに美しい自然環境と楽しさを提供します。フェアウェイとグリーンは非常にメンテナンスが行き届いており、ゴルフを楽しむための理想的な条件を提供します。クラブハウスには充実の施設があり、ゴルフ後のリラックスに最適です。BRGキングスアイランドのマウンテンビューコースは、ベトナムのゴルフ愛好家にとって魅力的な場所です。",
            "city": "ハノイ",
            "nameKana": "BRG キングス アイランド ゴルフ リゾート - マウンテン ビュー"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 1206,
            "address": "Bai Dai, Phu Quoc, Kien Giang Province, Viet Nam",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1531822471.jpg",
            "holeNum": 18,
            "minPrice": 2200000,
            "name": "Vinpearl Golf Club Phu Quoc",
            "originalPrice": 2900000,
            "bookingPolicy": "Fastee's Policy",
            "region": 3,
            "partnerType": "1",
            "star": 4,
            "aboutUsUrl": "https://vinpearl.com/vi/vingolf",
            "id": 151,
            "giaOriginalNgayCuoiTuan": 3500000,
            "giaNgayCuoiTuan": 2650000,
            "giaOriginalNgayLe": 2900000,
            "giaNgayLe": 2200000,
            "giaOriginalNgayThuong": 2375000,
            "giaNgayThuong": 1700000,
            "describe": "ヴィンパールゴルフクラブフーコックは、ベトナムのフーコック島に位置し、美しいビーチフロントと高品質なゴルフプレイを提供します。このコースは、トロピカルなリゾート体験とゴルフの組み合わせで、ゴルファーにとって理想的な場所です。フェアウェイとグリーンは高品質で、ゴルフを楽しむための素晴らしい環境を提供します。クラブハウスには充実の施設があり、ゴルフ以外のアクティビティも楽しめます。フーコック島での滞在中に、ヴィンパールゴルフを楽しんでください。",
            "city": "フーコック",
            "nameKana": "ヴィンパール ゴルフ クラブ フークオック"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 98,
            "address": "Vu Yen Island, Hai Phong, Viet Nam",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1531822510.jpg",
            "holeNum": 18,
            "minPrice": 2200000,
            "name": "Vinpearl Golf Hai Phong (Vu Yen)",
            "originalPrice": 2635000,
            "bookingPolicy": "policy",
            "region": 1,
            "partnerType": "1",
            "star": 4,
            "aboutUsUrl": "https://vinpearl.com/vi/vingolf",
            "id": 152,
            "giaOriginalNgayCuoiTuan": 3900000,
            "giaNgayCuoiTuan": 2650000,
            "giaOriginalNgayThuong": 3435000,
            "giaNgayThuong": 2200000,
            "describe": "ヴィンパールゴルフハイフォン（ヴィューエン）は、ベトナムのハイフォンに位置し、美しい海岸線と高品質なゴルフプレイを提供します。このコースは、ゴルフプレイヤーにリゾート体験とゴルフの両方を提供します。フェアウェイとグリーンは高品質で、ゴルフを楽しむための理想的な条件を提供します。クラブハウスには充実の施設があり、ゴルフ後のリラックスに最適です。ヴィンパールゴルフハイフォン（ヴィューエン）は、ベトナムのゴルフ愛好家にとって魅力的な場所です。",
            "city": "ハイフォン",
            "nameKana": "ヴィンパール ゴルフ ハイフォン (ヴー イェン)"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 1119,
            "address": "No. 145, Highway 822, Chanh Hamlet, Tan My Commune, Duc Hoa District, Long An Province",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1562572030.jpg",
            "holeNum": 18,
            "minPrice": 1600000,
            "name": "West Lakes Golf & Villa - Long An",
            "originalPrice": 1600000,
            "bookingPolicy": "Fastee's Policy",
            "region": 3,
            "partnerType": "1",
            "star": 3,
            "aboutUsUrl": "https://westlakesgolf.com/",
            "id": 132,
            "giaOriginalNgayCuoiTuan": 1600000,
            "giaNgayCuoiTuan": 2500000,
            "giaOriginalNgayLe": 3100000,
            "giaNgayLe": 1800000,
            "giaOriginalNgayThuong": 3100000,
            "giaNgayThuong": 1550000,
            "describe": "ウェストレイクゴルフ＆ヴィラ（ロンアン）は、ベトナムのロンアンに位置し、美しいゴルフコースと高品質なプレイを提供します。このコースは、フェアウェイとグリーンが非常によくメンテナンスされており、ゴルフを楽しむための理想的な場所です。クラブハウスは快適で、ゴルフ後にくつろぐことができます。ウェストレイクゴルフ＆ヴィラ（ロンアン）は、ベトナムのゴルフ愛好家にとって魅力的な選択肢の1つです。",
            "city": "ロンアン",
            "nameKana": "ウェスト レイクス ゴルフ & ヴィラ - ロング アン"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 605,
            "address": "An Sơn, Hoà Ninh, Hòa Vang, Đà Nẵng   16.018778, 108.048998",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1561817428.jpg",
            "holeNum": 18,
            "minPrice": 1900000,
            "name": "Ba Na Hills Golf Club",
            "originalPrice": 3100000,
            "bookingPolicy": "Fastee's Policy",
            "region": 2,
            "partnerType": "1",
            "star": 5,
            "aboutUsUrl": "https://banahillsgolf.com/vi/the-course/",
            "id": 130,
            "giaOriginalNgayCuoiTuan": 4100000,
            "giaNgayCuoiTuan": 2700000,
            "giaOriginalNgayLe": 3100000,
            "giaNgayLe": 2400000,
            "giaOriginalNgayThuong": 3100000,
            "giaNgayThuong": 1900000,
            "describe": "バナヒルズゴルフクラブは、ベトナムのダナンに位置し、美しい山岳地帯の中にあるゴルフコースです。このコースは、自然の美しさと挑戦的なプレイを楽しむための理想的な場所です。フェアウェイとグリーンは高品質でメンテナンスが行き届いており、ゴルフプレイヤーに素晴らしい環境を提供します。クラブハウスは快適で、ゴルフ後のリラックスに最適です。ダナンでの滞在中に、バナヒルズゴルフクラブを訪れてみてください。",
            "city": "ダナン",
            "nameKana": "バ ナ ヒルズ ゴルフ クラブ"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 1065,
            "address": "Hồ Đạ Ròn, Đạ Ròn, Đơn Dương, Lâm Đồng, Việt Nam",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1559819571.jpg",
            "holeNum": 18,
            "minPrice": 1850000,
            "name": "Dalat at 1200 Golf Club",
            "originalPrice": 2350000,
            "bookingPolicy": "Fastee's Policy",
            "region": 2,
            "partnerType": "1",
            "star": 4,
            "aboutUsUrl": "http://www.dalat1200.com/",
            "id": 124,
            "giaOriginalNgayCuoiTuan": 3160000,
            "giaNgayCuoiTuan": 2400000,
            "giaOriginalNgayLe": 3160000,
            "giaNgayLe": 1850000,
            "giaOriginalNgayThuong": 2150000,
            "giaNgayThuong": 1850000,
            "describe": "ダラットアット1200ゴルフクラブは、ベトナムのダラットに位置し、美しい山岳地帯の中にあるゴルフコースです。このコースは、ゴルフプレイヤーに自然の美しさと楽しさを提供します。フェアウェイとグリーンは非常にメンテナンスが行き届いており、ゴルフを楽しむための理想的な条件を提供します。クラブハウスは快適で、リラックスできる場所です。ダラットでの滞在中に、ダラットアット1200ゴルフクラブを訪れてみてください。",
            "city": "ダラット",
            "nameKana": "ダラット アット 1200 ゴルフ クラブ"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 621,
            "address": "Điện Ngọc, Điện Bàn, Quảng Nam",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1559813121.jpg",
            "holeNum": 18,
            "minPrice": 2350000,
            "name": "Montgomerie Links Vietnam",
            "originalPrice": 2800000,
            "bookingPolicy": "Fastee's Policy",
            "region": 2,
            "partnerType": "1",
            "star": 5,
            "aboutUsUrl": "https://www.montgomerielinks.com/",
            "id": 123,
            "giaOriginalNgayCuoiTuan": 4500000,
            "giaNgayCuoiTuan": 2600000,
            "giaOriginalNgayLe": 2800000,
            "giaNgayLe": 2600000,
            "giaOriginalNgayThuong": 2800000,
            "giaNgayThuong": 2350000,
            "describe": "モンゴメリーリンクスベトナムは、ベトナムのクイニョンに位置し、美しい海岸線の景色と高品質なゴルフプレイを提供します。このコースは、ゴルフプレイヤーにリゾート体験とゴルフの両方を提供します。フェアウェイとグリーンは高品質で、ゴルフを楽しむための理想的な条件を提供します。クラブハウスには充実の施設があり、ゴルフ後のリラックスに最適です。モンゴメリーリンクスベトナムは、クイニョンでのゴルフ体験を求めるゴルファーにとって魅力的な選択肢です。",
            "city": "クアンナム",
            "nameKana": "モンゴメリー リンクス ベトナム"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 1055,
            "address": "Phân khu chức năng số 7 & 8, Khu du lịch Hồ Tuyền Lâm, Phường 3, Thành phố Đà Lạt, Lâm Đồng, Việt Nam",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1557735079.jpg",
            "holeNum": 18,
            "minPrice": 2050000,
            "name": "SAM Tuyen Lam Golf & Resorts",
            "originalPrice": 2500000,
            "bookingPolicy": "Fastee's Policy",
            "region": 2,
            "partnerType": "1",
            "star": 5,
            "aboutUsUrl": "https://samtuyenlamgolf.com.vn/",
            "id": 112,
            "giaOriginalNgayCuoiTuan": 2600000,
            "giaNgayCuoiTuan": 2450000,
            "giaOriginalNgayLe": 2600000,
            "giaNgayLe": 2050000,
            "giaOriginalNgayThuong": 2200000,
            "giaNgayThuong": 2050000,
            "describe": "SAMトゥエンラムゴルフ＆リゾートは、ベトナムのダラットに位置し、美しい山岳地帯と湖畔の景色に囲まれたゴルフコースです。このコースは、ゴルフプレイヤーに自然の美しさと楽しさを提供します。フェアウェイとグリーンは高品質でメンテナンスが行き届いており、ゴルフを楽しむための理想的な条件を提供します。クラブハウスは快適で、ゴルフ後のリラックスに最適です。ダラットでの滞在中に、SAMトゥエンラムゴルフ＆リゾートを訪れてみてください。",
            "city": "ダラット",
            "nameKana": "SAM トゥエン ラム ゴルフ & リゾーツ"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 102,
            "address": "Thôn 4B, xã Đông Sơn, Thành Phố Tam Điệp, tỉnh Ninh Bình",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1561000683.jpg",
            "holeNum": 18,
            "minPrice": 1650000,
            "name": "Royal Golf Club (Yen Thang)",
            "originalPrice": 1700000,
            "bookingPolicy": "Fastee's Policy",
            "region": 1,
            "partnerType": "1",
            "star": 3,
            "aboutUsUrl": "http://royalgolf.com.vn/",
            "id": 105,
            "giaOriginalNgayCuoiTuan": 2700000,
            "giaNgayCuoiTuan": 2650000,
            "giaOriginalNgayLe": 2700000,
            "giaNgayLe": 2650000,
            "giaOriginalNgayThuong": 1700000,
            "giaNgayThuong": 1650000,
            "describe": "ロイヤルゴルフクラブ（イェンタン）は、ベトナムのイェンタンに位置し、美しい山岳地帯と湖畔の景色に囲まれたゴルフコースです。このコースは、自然の美しさとゴルフプレイを楽しむための理想的な場所です。フェアウェイとグリーンは高品質でメンテナンスが行き届いており、ゴルフプレイヤーに素晴らしい環境を提供します。クラブハウスは快適で、リラックスできる場所です。イェンタンでの滞在中に、ロイヤルゴルフクラブを訪れてみてください。",
            "city": "タムディエップ",
            "nameKana": "ロイヤル ゴルフ クラブ (イエン タン)"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 569,
            "address": "Thôn Cù Dù, Xã Lộc Vĩnh, Huyện Phú Lộc, Tỉnh Thừa Thiên Huế, Việt Nam",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1557299493.jpg",
            "holeNum": 18,
            "minPrice": 1700000,
            "name": "Laguna Lang Co Golf Course",
            "originalPrice": 2600000,
            "bookingPolicy": "Fastee's Policy",
            "region": 2,
            "partnerType": "1",
            "star": 3,
            "aboutUsUrl": "https://www.lagunalangco.com/vi/san-gon/",
            "id": 104,
            "giaOriginalNgayCuoiTuan": 3280000,
            "giaNgayCuoiTuan": 2400000,
            "giaOriginalNgayLe": 2600000,
            "giaNgayLe": 2400000,
            "giaOriginalNgayThuong": 2600000,
            "giaNgayThuong": 1700000,
            "describe": "ラグナランコゴルフコースは、ベトナムのランコに位置し、美しい海岸線の景色と高品質なゴルフプレイを提供します。このコースは、ゴルフプレイヤーにリゾート体験とゴルフの両方を提供します。フェアウェイとグリーンは高品質で、ゴルフを楽しむための理想的な条件を提供します。クラブハウスには充実の施設があり、ゴルフ後のリラックスに最適です。ランコでの滞在中に、ラグナランコゴルフコースを訪れてみてください。",
            "city": "ホイアン",
            "nameKana": "ラグーナ ラン ゴ ゴルフ コース"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 238,
            "address": "Trà Cổ, Tràng Vĩ, P. Trà Cổ, Móng Cái,",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1557221330.jpg",
            "holeNum": 18,
            "minPrice": 1450000,
            "name": "Mong Cai International Golf Club",
            "originalPrice": 1880000,
            "bookingPolicy": "Fastee's Policy",
            "region": 1,
            "partnerType": "1",
            "star": 4,
            "aboutUsUrl": "https://golftimes.vn/cam-nhan-san-golf-quoc-te-mong-cai-vinh-thuan-426.html",
            "id": 103,
            "giaOriginalNgayCuoiTuan": 2530000,
            "giaNgayCuoiTuan": 1650000,
            "giaOriginalNgayLe": 1880000,
            "giaNgayLe": 1650000,
            "giaOriginalNgayThuong": 1880000,
            "giaNgayThuong": 1450000,
            "describe": "モンカイインターナショナルゴルフクラブは、ベトナムのモンカイに位置し、美しい海岸線の景色と高品質なゴルフプレイを提供します。このコースは、トロピカルなリゾート体験とゴルフを楽しむための素晴らしい場所です。フェアウェイとグリーンは非常にメンテナンスが行き届いており、ゴルフを楽しむための理想的な条件を提供します。クラブハウスは快適で、ゴルフ後のくつろぎに最適です。モンカイでの滞在中に、モンカイインターナショナルゴルフクラブを訪れてみてください。",
            "city": "モンカイ",
            "nameKana": "モン カイ インターナショナル ゴルフ クラブ"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 106,
            "address": "ĐT 353, KDC số 8, Hải Phòng",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1561705930.jpg",
            "holeNum": 18,
            "minPrice": 2330000,
            "name": "BRG Ruby Tree Golf Resort",
            "originalPrice": 2850000,
            "bookingPolicy": "Fastee's Policy",
            "region": 1,
            "partnerType": "1",
            "star": 4,
            "aboutUsUrl": "http://brgrubytreegolf.vn/1/15/Trang-chu.aspx",
            "id": 129,
            "giaOriginalNgayCuoiTuan": 3475000,
            "giaNgayCuoiTuan": 3250000,
            "giaOriginalNgayLe": 3475000,
            "giaNgayLe": 3250000,
            "giaOriginalNgayThuong": 2850000,
            "giaNgayThuong": 2330000,
            "describe": "BRGルビーツリーゴルフリゾートは、ベトナムのフーコックに位置し、美しい海岸線の景色と高品質なゴルフプレイを提供します。このコースは、ゴルフプレイヤーにリゾート体験とゴルフの両方を提供します。フェアウェイとグリーンは高品質で、ゴルフを楽しむための素晴らしい環境を提供します。クラブハウスには充実の施設があり、ゴルフ後のリラックスに最適です。フーコックでの滞在中に、BRGルビーツリーゴルフリゾートを訪れてみてください。",
            "city": "ハイフォン",
            "nameKana": "BRG ルビー トゥリー ゴルフ リゾート"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 136,
            "address": "Đường Nguyễn Văn Cừ, phường Hồng Hà, thành phố Hạ Long, tỉnh Quảng Ninh",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1556080431.jpg",
            "holeNum": 18,
            "minPrice": 1600000,
            "name": "FLC Ha Long Golf Club",
            "originalPrice": 1900000,
            "bookingPolicy": "Chính sách hoãn hủy:\n\n1. Trên 72 tiếng trước Giờ Phát Bóng - (Không thu phí).\n\n2. Từ 48 tiếng đến 72 tiếng trước Giờ Phát Bóng - (50% Phí Dịch Vụ Golf đã thanh toán).\n\n3. Dưới 48 tiếng trước Giờ Phát Bóng - (100% Phí Dịch Vụ Golf đã thanh toán).\n\nNotice Time (for change/ cancellation/ or no show):\n\n1. Before 72 hours prior to the Tee Time. - (None).\n\n2. From 72 hours up to 48 hours prior to the Tee Time - (50% of the Service Fee prepayment ).\n\n3. Within 48 hours prior to the Tee Time - (100% of the Service Fee prepayment ).\n\nLưu ý: Với các booking có thanh toán lẻ xe điện, khách hàng vui lòng thanh toán phí lẻ xe trực tiếp tại sân golf.",
            "region": 1,
            "partnerType": "1",
            "star": 4,
            "aboutUsUrl": "https://flcbiscom.com/vi/trang-chu/",
            "id": 97,
            "giaOriginalNgayCuoiTuan": 3700000,
            "giaNgayCuoiTuan": 3650000,
            "giaOriginalNgayThuong": 2500000,
            "giaNgayThuong": 1800000,
            "describe": "FLCハロンゴルフクラブは、ベトナムのハロンに位置し、美しい海岸線の景色と高品質なゴルフプレイを提供します。このコースは、ゴルフプレイヤーにリゾート体験とゴルフの両方を提供します。フェアウェイとグリーンは非常にメンテナンスが行き届いており、ゴルフを楽しむための理想的な条件を提供します。クラブハウスには充実の施設があり、ゴルフ後のリラックスに最適です。ハロンでの滞在中に、FLCハロンゴルフクラブを訪れてみてください。",
            "city": "ハロン",
            "nameKana": "FLC ハロン ゴルフ クラブ"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 875,
            "address": "Khu 4, Nhơn Lý - Bãi biển Cát Tiến, xã Nhơn Lý Thành phố Quy Nhơn, tỉnh Bình Định, Việt Nam",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1556264119.jpg",
            "holeNum": 18,
            "minPrice": 1750000,
            "name": "FLC Quy Nhon Golf Links",
            "originalPrice": 2200000,
            "bookingPolicy": "Chính sách hoãn hủy:\n\n1. Trên 72 tiếng trước Giờ Phát Bóng - (Không thu phí).\n\n2. Từ 48 tiếng đến 72 tiếng trước Giờ Phát Bóng - (50% Phí Dịch Vụ Golf đã thanh toán).\n\n3. Dưới 48 tiếng trước Giờ Phát Bóng - (100% Phí Dịch Vụ Golf đã thanh toán).\n\nNotice Time (for change/ cancellation/ or no show):\n\n1. Before 72 hours prior to the Tee Time. - (None).\n\n2. From 72 hours up to 48 hours prior to the Tee Time - (50% of the Service Fee prepayment ).\n\n3. Within 48 hours prior to the Tee Time - (100% of the Service Fee prepayment ).\n\nLưu ý: Với các booking có thanh toán lẻ xe điện, khách hàng vui lòng thanh toán phí lẻ xe trực tiếp tại sân golf.",
            "region": 2,
            "partnerType": "1",
            "star": 4,
            "aboutUsUrl": "https://flcbiscom.com/portfolio/flc-quynhon/",
            "id": 99,
            "giaOriginalNgayCuoiTuan": 2800000,
            "giaNgayCuoiTuan": 2100000,
            "giaOriginalNgayLe": 2200000,
            "giaNgayLe": 1750000,
            "giaOriginalNgayThuong": 2200000,
            "giaNgayThuong": 1750000,
            "describe": "FLCクイニョンゴルフリンクスは、ベトナムのクイニョンに位置し、美しい海岸線の景色と高品質なゴルフプレイを提供します。このコースは、トロピカルなリゾート体験とゴルフの組み合わせで、ゴルファーにとって理想的な場所です。フェアウェイとグリーンは高品質で、ゴルフを楽しむための素晴らしい環境を提供します。クラブハウスには充実の施設があり、ゴルフ以外のアクティビティも楽しめます。クイニョンでの滞在中に、FLCクイニョンゴルフリンクスを訪れてみてください。",
            "city": "クイニョン",
            "nameKana": "FLC クイ ニョン ゴルフ リンクス"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 421,
            "address": "Xã Hải Ninh, huyện Quảng Ninh, tỉnh Quảng Bình, Việt Nam",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1556264905.jpg",
            "holeNum": 18,
            "minPrice": 1750000,
            "name": "FLC Quang Binh Golf Links",
            "originalPrice": 2200000,
            "bookingPolicy": "Chính sách hoãn hủy:\n\n1. Trên 72 tiếng trước Giờ Phát Bóng - (Không thu phí).\n\n2. Từ 48 tiếng đến 72 tiếng trước Giờ Phát Bóng - (50% Phí Dịch Vụ Golf đã thanh toán).\n\n3. Dưới 48 tiếng trước Giờ Phát Bóng - (100% Phí Dịch Vụ Golf đã thanh toán).\n\nNotice Time (for change/ cancellation/ or no show):\n\n1. Before 72 hours prior to the Tee Time. - (None).\n\n2. From 72 hours up to 48 hours prior to the Tee Time - (50% of the Service Fee prepayment ).\n\n3. Within 48 hours prior to the Tee Time - (100% of the Service Fee prepayment ).\n\nLưu ý: Với các booking có thanh toán lẻ xe điện, khách hàng vui lòng thanh toán phí lẻ xe trực tiếp tại sân golf.",
            "region": 2,
            "partnerType": "1",
            "star": 3,
            "aboutUsUrl": "https://flcbiscom.com/portfolio/flc-quangbinh/",
            "id": 100,
            "giaOriginalNgayCuoiTuan": 2800000,
            "giaNgayCuoiTuan": 2100000,
            "giaOriginalNgayLe": 2200000,
            "giaNgayLe": 1750000,
            "giaOriginalNgayThuong": 2200000,
            "giaNgayThuong": 1750000,
            "describe": "FLCクオンビンゴルフリンクスは、ベトナムのクオンビンに位置し、美しい海岸線の景色と高品質なゴルフプレイを提供します。このコースは、ゴルフプレイヤーにリゾート体験とゴルフの両方を提供します。フェアウェイとグリーンは非常にメンテナンスが行き届いており、ゴルフを楽しむための理想的な条件を提供します。クラブハウスには充実の施設があり、ゴルフ後のリラックスに最適です。クオンビンでの滞在中に、FLCクオンビンゴルフリンクスを訪れてみてください。",
            "city": "クアンビン",
            "nameKana": "FLC クアン ビン ゴルフ リンクス"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 140,
            "address": "Đường Hồ Xuân Hương, Sầm Sơn, Thanh Hóa, Việt Nam",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1556263593.JPG",
            "holeNum": 18,
            "minPrice": 1750000,
            "name": "FLC Sam Son Golf Links",
            "originalPrice": 2200000,
            "bookingPolicy": "Chính sách hoãn hủy:\n\n1. Trên 72 tiếng trước Giờ Phát Bóng - (Không thu phí).\n\n2. Từ 48 tiếng đến 72 tiếng trước Giờ Phát Bóng - (50% Phí Dịch Vụ Golf đã thanh toán).\n\n3. Dưới 48 tiếng trước Giờ Phát Bóng - (100% Phí Dịch Vụ Golf đã thanh toán).\n\nNotice Time (for change/ cancellation/ or no show):\n\n1. Before 72 hours prior to the Tee Time. - (None).\n\n2. From 72 hours up to 48 hours prior to the Tee Time - (50% of the Service Fee prepayment ).\n\n3. Within 48 hours prior to the Tee Time - (100% of the Service Fee prepayment ).\n\nLưu ý: Với các booking có thanh toán lẻ xe điện, khách hàng vui lòng thanh toán phí lẻ xe trực tiếp tại sân golf.",
            "region": 1,
            "partnerType": "1",
            "star": 3,
            "aboutUsUrl": "https://flcbiscom.com/portfolio/flc-samson/",
            "id": 98,
            "giaOriginalNgayCuoiTuan": 2800000,
            "giaNgayCuoiTuan": 2650000,
            "giaOriginalNgayLe": 2200000,
            "giaNgayLe": 1750000,
            "giaOriginalNgayThuong": 2200000,
            "giaNgayThuong": 1750000,
            "describe": "FLCサムソンゴルフリンクスは、ベトナムのサムソンに位置し、美しい海岸線の景色と高品質なゴルフプレイを提供します。このコースは、トロピカルなリゾート体験とゴルフの組み合わせで、ゴルファーにとって理想的な場所です。フェアウェイとグリーンは高品質で、ゴルフを楽しむための素晴らしい環境を提供します。クラブハウスには充実の施設があり、ゴルフ以外のアクティビティも楽しめます。サムソンでの滞在中に、FLCサムソンゴルフリンクスを訪れてみてください。",
            "city": "タンホア",
            "nameKana": "FLC サム ソン ゴルフ リンクス"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 1148,
            "address": "Ong Con Island. Dai Phuoc Commune, Nhon Trach District, Dong Nai Province",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1531821704.jpg",
            "holeNum": 18,
            "minPrice": 1950000,
            "name": "Taekwang Jeongsan Country Club",
            "originalPrice": 2000000,
            "bookingPolicy": "Fastee's Policy",
            "region": 3,
            "partnerType": "1",
            "star": 4,
            "aboutUsUrl": "https://www.facebook.com/Jeongsancc/",
            "id": 144,
            "giaOriginalNgayCuoiTuan": 3000000,
            "giaNgayCuoiTuan": 2950000,
            "giaOriginalNgayLe": 3000000,
            "giaNgayLe": 2950000,
            "giaOriginalNgayThuong": 2000000,
            "giaNgayThuong": 1950000,
            "describe": "タエクワンジョンサンカントリークラブは、ベトナムのホーチミン市に位置し、美しいゴルフコースと高品質なゴルフプレイを提供します。このコースは、フェアウェイとグリーンが非常にメンテナンスが行き届いており、ゴルフを楽しむための理想的な場所です。クラブハウスは快適で、ゴルフ後にくつろぐことができます。ホーチミン市でのゴルフ体験を求めるゴルファーにとって、タエクワンジョンサンカントリークラブは魅力的な選択肢の1つです。",
            "city": "ドンナイ",
            "nameKana": "タエクワン ジョンサン カントリー クラブ"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 122,
            "address": "Khu vui chơi giải trí quốc tế Tuần Châu, tại phường Tuần Châu, Hạ Long.",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2021/09/book-san-golf-tuan-chau-ha-long.jpeg",
            "holeNum": 18,
            "minPrice": 2000000,
            "name": "Tuần Châu Golf & Resort",
            "originalPrice": 2500000,
            "bookingPolicy": "Update.",
            "region": 1,
            "partnerType": "1",
            "star": 4,
            "aboutUsUrl": "http://tuanchaugolfresort.vn/",
            "id": 193,
            "giaOriginalNgayCuoiTuan": 3550000,
            "giaNgayCuoiTuan": 3350000,
            "giaOriginalNgayLe": 2500000,
            "giaNgayLe": 2000000,
            "giaOriginalNgayThuong": 2500000,
            "giaNgayThuong": 2000000,
            "describe": "トゥアンチャウゴルフ＆リゾートは、ベトナムのハロン湾に位置し、美しい海岸線の景色と高品質なゴルフプレイを提供します。このコースは、ゴルフプレイヤーにトロピカルなリゾート体験とゴルフの両方を提供します。フェアウェイとグリーンは高品質で、ゴルフを楽しむための素晴らしい環境を提供します。クラブハウスには充実の施設があり、ゴルフ後のリラックスに最適です。ハロン湾での滞在中に、トゥアンチャウゴルフ＆リゾートを訪れてみてください。",
            "city": "ハロン",
            "nameKana": "トゥアン チャウ ゴルフ & リゾート"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 41,
            "address": "Thanh Lanh, Trung Mỹ, Bình Xuyên, Vĩnh Phúc",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2021/09/241004661_1039979923207850_8586993597052248877_n.jpeg",
            "holeNum": 18,
            "minPrice": 2100000,
            "name": "Thanh Lanh Valley Golf & Resort",
            "originalPrice": 2250000,
            "bookingPolicy": "Update.",
            "region": 1,
            "partnerType": "1",
            "star": 4,
            "aboutUsUrl": "https://www.facebook.com/thanhlanhvalleygolfandresort",
            "id": 194,
            "giaOriginalNgayCuoiTuan": 3550000,
            "giaNgayCuoiTuan": 3400000,
            "giaOriginalNgayLe": 3550000,
            "giaNgayLe": 3400000,
            "giaOriginalNgayThuong": 2550000,
            "giaNgayThuong": 2300000,
            "describe": "タンランバレーゴルフ＆リゾートは、ベトナムのホーチミン市に位置し、美しいゴルフコースと高品質なゴルフプレイを提供します。このコースは、ゴルフプレイヤーにフェアウェイとグリーンが非常にメンテナンスが行き届いており、ゴルフを楽しむための理想的な場所です。クラブハウスは快適で、ゴルフ後にくつろぐことができます。ホーチミン市でのゴルフ体験を求めるゴルファーにとって、タンランバレーゴルフ＆リゾートは魅力的な選択肢の1つです。",
            "city": "ビンフック",
            "nameKana": "タン ラン バレー ゴルフ & リゾート"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 1158,
            "address": "Phan Thiết, Bình Thuận",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2021/05/PGA-Golf-NovaWorld-Phan-Thiet-36-lo-hole-quoc-te-san-Garden.jpg",
            "holeNum": 18,
            "minPrice": 1800000,
            "name": "PGA Golf Villas Novaworld Phan Thiết",
            "originalPrice": 2100000,
            "bookingPolicy": "Chính sách hoãn hủy đang được cập nhật !",
            "region": 3,
            "partnerType": "1",
            "star": 2,
            "aboutUsUrl": "",
            "id": 163,
            "giaOriginalNgayCuoiTuan": 2900000,
            "giaNgayCuoiTuan": 2700000,
            "giaOriginalNgayLe": 1900000,
            "giaNgayLe": 1800000,
            "giaOriginalNgayThuong": 1900000,
            "giaNgayThuong": 1800000,
            "describe": "PGAゴルフビラズノバワールドファンティエットは、ベトナムのファンティエットに位置し、美しいゴルフコースと高品質なゴルフプレイを提供します。このコースは、ゴルフプレイヤーにトロピカルなリゾート体験とゴルフの両方を提供します。フェアウェイとグリーンは高品質で、ゴルフを楽しむための素晴らしい環境を提供します。クラブハウスには充実の施設があり、ゴルフ後のリラックスに最適です。ファンティエットでの滞在中に、PGAゴルフビラズノバワールドファンティエットを訪れてみてください。",
            "city": "ファンティエット",
            "nameKana": "PGA ゴルフ ヴィラズ ノヴァワールド ファン ティエット"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 50,
            "address": "TT. Kỳ Sơn, Kỳ Sơn, Hoa Binh",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1554706779.jpg",
            "holeNum": 18,
            "minPrice": 1700000,
            "name": "Hilltop Valley Golf Club",
            "originalPrice": 1850000,
            "bookingPolicy": "Fastee's Policy",
            "region": 1,
            "partnerType": "1",
            "star": 4,
            "aboutUsUrl": "http://hilltopvalleygolf.com/",
            "id": 91,
            "giaOriginalNgayCuoiTuan": 3000000,
            "giaNgayCuoiTuan": 3050000,
            "giaOriginalNgayLe": 3000000,
            "giaNgayLe": 3050000,
            "giaOriginalNgayThuong": 2000000,
            "giaNgayThuong": 1950000,
            "describe": "ヒルトップバレーゴルフクラブは、ベトナムのダラットに位置し、美しい山岳地帯と湖畔の景色に囲まれたゴルフコースです。このコースは、自然の美しさとゴルフプレイを楽しむための理想的な場所です。フェアウェイとグリーンは高品質でメンテナンスが行き届いており、ゴルフを楽しむための理想的な条件を提供します。クラブハウスは快適で、ゴルフ後のリラックスに最適です。ダラットでの滞在中に、ヒルトップバレーゴルフクラブを訪れてみてください。",
            "city": "ホアビン",
            "nameKana": "ヒルトップ バレー ゴルフ クラブ"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 46,
            "address": "Hop Chau commune, Tam Dao district, Vinh Phuc province",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1554706745.jpg",
            "holeNum": 18,
            "minPrice": 1550000,
            "name": "Tam Dao Golf & Resort",
            "originalPrice": 1550000,
            "bookingPolicy": "Fastee's policy",
            "region": 1,
            "partnerType": "1",
            "star": 3,
            "aboutUsUrl": "http://tamdaogolf.com/",
            "id": 75,
            "giaOriginalNgayCuoiTuan": 3165000,
            "giaNgayCuoiTuan": 3000000,
            "giaOriginalNgayLe": 3165000,
            "giaNgayLe": 3000000,
            "giaOriginalNgayThuong": 2000000,
            "giaNgayThuong": 1700000,
            "describe": "Tam Dao Golf & Resortは、ベトナムのタムダオ山脈に位置する美しいゴルフコースとリゾートです。このリゾートは、自然の美しさに囲まれた静かな環境で、ゴルフ愛好家にとって究極のリラックスとエンターテイメントを提供します。コースは挑戦的でありながらも楽しいプレーを提供し、観光客にも大変人気があります。リゾート内には高級宿泊施設、レストラン、スパなどがあり、ゴルフ以外のアクティビティも楽しむことができます。",
            "city": "ヴィンフック",
            "nameKana": "タム ダオ ゴルフ & リゾート"
        },
        {
            "teeDate": "2023-07-20",
            "distance": 55,
            "address": "Nguyễn Du, Ba Sao, Kim Bảng, Hà Nam",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1554706837.jpg",
            "holeNum": 18,
            "minPrice": 1650000,
            "name": "Stone Valley Golf Resort (Kim Bang)",
            "originalPrice": 1800000,
            "bookingPolicy": "Fastee's Policy",
            "region": 1,
            "partnerType": "1",
            "star": 3,
            "aboutUsUrl": "http://www.golftruongan.vn/",
            "id": 94,
            "giaOriginalNgayThuong": 1800000,
            "giaNgayThuong": 1800000,
            "describe": "Stone Valley Golf Resortは、ベトナムのキンバン地区に位置する素晴らしいゴルフリゾートです。このリゾートは、美しい自然環境と高品質のゴルフコースを提供し、ゴルフ愛好家にとって理想的な場所です。コースは戦略的で挑戦的であり、すべてのスキルレベルのゴルファーに向いています。リゾート内には宿泊施設、レストラン、会議施設などがあり、ゴルフ以外のアクティビティも楽しむことができます。",
            "city": "ハナム",
            "nameKana": "ストーン バレー ゴルフ リゾート (キム バン)"
        },
        {
            "teeDate": "2023-07-21",
            "distance": 30,
            "address": "Sóc Sơn, Hà Nội, Việt Nam.",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1554708254.jpg",
            "holeNum": 18,
            "minPrice": 3000000,
            "name": "BRG Legend Hill Golf Resort",
            "originalPrice": 3750000,
            "bookingPolicy": "Fastee's Policy",
            "region": 1,
            "partnerType": "1",
            "star": 4,
            "aboutUsUrl": "http://brglegendhillgolf.vn/1/15/Trang-chu.aspx",
            "id": 95,
            "giaOriginalNgayCuoiTuan": 4455000,
            "giaNgayCuoiTuan": 4490000,
            "giaOriginalNgayLe": 4680000,
            "giaNgayLe": 4250000,
            "giaOriginalNgayThuong": 4680000,
            "giaNgayThuong": 3190000,
            "describe": "BRG Legend Hill Golf Resortは、ベトナムのゴルフコースとリゾートの中でも一流のものの一つです。このリゾートは高級感あふれる設備と美しい景観を提供し、ゴルファーと観光客のために快適な滞在を保証します。ゴルフコースは戦略的で技巧的であり、プレイヤーに挑戦を与えます。リゾート内には高級ヴィラ、スパ、レストラン、プールなどがあります。",
            "city": "ハノイ",
            "nameKana": "BRG レジェンド ヒル ゴルフ リゾート"
        },
        {
            "teeDate": "2023-07-21",
            "distance": 62,
            "address": "Thái Học, Chí Linh, Hải Dương",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1556879275.jpg",
            "holeNum": 18,
            "minPrice": 1950000,
            "name": "ChiLinh Golf",
            "originalPrice": 2990000,
            "bookingPolicy": "Fastee's Policy",
            "region": 1,
            "partnerType": "1",
            "star": 3,
            "aboutUsUrl": "https://chilinhgolf.com/",
            "id": 101,
            "giaOriginalNgayCuoiTuan": 3500000,
            "giaNgayCuoiTuan": 2900000,
            "giaOriginalNgayLe": 2990000,
            "giaNgayLe": 2900000,
            "giaOriginalNgayThuong": 1900000,
            "giaNgayThuong": 1700000,
            "describe": "ChiLinh Golfは、ベトナムの美しい自然環境の中に位置するゴルフコースです。このコースは、森林と湖に囲まれた風光明媚な場所で、ゴルフを楽しむのに最適です。挑戦的なコースデザインと豪華なクラブハウスを備え、ゴルファーに高品質なプレー体験を提供します。",
            "city": "ハイズオン",
            "nameKana": "チーリン ゴルフ"
        },
        {
            "teeDate": "2023-07-21",
            "distance": 1128,
            "address": "77 Đại lộ Bình Dương, Lái Thiêu, Thị xã Thuận An, Bình Dương",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1559288853.jpg",
            "holeNum": 18,
            "minPrice": 2320000,
            "name": "Song Be Golf Resort",
            "originalPrice": 3150000,
            "bookingPolicy": "Fastee's Policy",
            "region": 3,
            "partnerType": "1",
            "star": 3,
            "aboutUsUrl": "https://www.songbegolf.com/main/",
            "id": 141,
            "giaOriginalNgayCuoiTuan": 3400000,
            "giaNgayCuoiTuan": 3150000,
            "giaOriginalNgayLe": 3150000,
            "giaNgayLe": 2350000,
            "giaOriginalNgayThuong": 2250000,
            "giaNgayThuong": 2350000,
            "describe": "Song Be Golf Resortは、ベトナムのゴルフリゾートの古典的な選択肢の一つです。このリゾートは長年にわたりゴルファーに愛されており、美しいコースとリラックスした雰囲気で知られています。ゴルフ以外にも、レストランや宿泊施設も充実しており、家族や友人と楽しむのに最適です。",
            "city": "ビンズオン",
            "nameKana": "ソン ベ ゴルフ リゾート"
        },
        {
            "teeDate": "2023-07-21",
            "distance": 20,
            "address": "Khu Du lịch Quốc tế Đồi Rồng - Dragon Ocean Đồ Sơn, Hải Phòng",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2023/07/dragon_golf_links.jpeg",
            "holeNum": 18,
            "minPrice": 1600000,
            "name": "Dragon Golf Links",
            "originalPrice": 1900000,
            "bookingPolicy": "Fastee's Policy",
            "region": 1,
            "partnerType": "1",
            "star": 1,
            "aboutUsUrl": "https://www.facebook.com/dragongolflinks/",
            "id": 207,
            "giaOriginalNgayCuoiTuan": 2700000,
            "giaNgayCuoiTuan": 2800000,
            "giaOriginalNgayLe": 1900000,
            "giaNgayLe": 1900000,
            "giaOriginalNgayThuong": 1900000,
            "giaNgayThuong": 1900000,
            "describe": "Dragon Golf Linksは、ベトナムのゴルフシーンで注目を集めているリゾートの一つです。美しい海岸線に沿った風光明媚なコースで、ゴルファーに素晴らしいプレー体験を提供します。挑戦的なコースデザインと壮観な景色が特徴で、ゴルフラウンドを楽しむのに最適です。",
            "city": "ハイフォン",
            "nameKana": "ドラゴン ゴルフ リンクス"
        },
        {
            "teeDate": "2023-07-21",
            "distance": 45,
            "address": "Tượng Lĩnh, Kim Bảng, Hà Nam",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2023/07/legend_valley-min.jpeg",
            "holeNum": 18,
            "minPrice": 2200000,
            "name": "Legend Valley Country Club",
            "originalPrice": 2600000,
            "bookingPolicy": "Fastee's Policy",
            "region": 1,
            "partnerType": "1",
            "star": 1,
            "aboutUsUrl": "http://legendvalleycountryclub.vn/",
            "id": 208,
            "giaOriginalNgayCuoiTuan": 3400000,
            "giaNgayCuoiTuan": 2800000,
            "giaOriginalNgayLe": 1900000,
            "giaNgayLe": 2800000,
            "giaOriginalNgayThuong": 2600000,
            "giaNgayThuong": 2200000,
            "describe": "Legend Valley Country Clubは、ベトナムのゴルフとリラクゼーションを組み合わせた場所です。リゾート内には高品質なゴルフコース、宿泊施設、スパ、レストランなどがあり、ゴルフ以外のアクティビティも楽しむことができます。ゴルファーと観光客のために充実した滞在を提供します。",
            "city": "ハナム",
            "nameKana": "レジェンド バレー カントリー クラブ"
        },
        {
            "teeDate": "2023-07-21",
            "distance": 90,
            "address": "Lưu Kiếm, Thủy Nguyên, Hải Phòng",
            "cover": "https://fastee-media.s3.amazonaws.com/media/2019/07/1557220504.jpg",
            "holeNum": 18,
            "minPrice": 1930000,
            "name": "Sono Belle Hai Phong (Sông Giá Golf Resort)",
            "originalPrice": 2850000,
            "bookingPolicy": "Fastee's Policy",
            "region": 1,
            "partnerType": "1",
            "star": 3,
            "aboutUsUrl": "https://www.facebook.com/Sonobellehaiphong/",
            "id": 102,
            "giaOriginalNgayCuoiTuan": 3050000,
            "giaNgayCuoiTuan": 2700000,
            "giaOriginalNgayLe": 2970000,
            "giaNgayLe": 2950000,
            "giaOriginalNgayThuong": 2100000,
            "giaNgayThuong": 1700000,
            "describe": "Sono Belle Hai Phong（またはSông Giá Golf Resort）は、ベトナムのハイフォン市に位置するゴルフリゾートです。このリゾートは高級宿泊施設、美しいゴルフコース、レストラン、スパなどを提供し、ゴルファーと観光客のために贅沢な滞在を提供します。ゴルフを楽しむだけでなく、リゾート内でのくつろぎも楽しむことができます。",
            "city": "ハイフォン",
            "nameKana": "ソノ ベル ハイフォン (ソン ジア ゴルフ リゾート)"
        }
    ];